/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn tcpip_init_done(arg1: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn wait_for_tcpip_init() -> ::std::os::raw::c_int;
}
