/* automatically generated by rust-bindgen 0.72.1 */

pub const VIDEO_MODE_AUTO: i32 = -1;
pub const VIDEO_MODE_PAL50: u32 = 0;
pub const VIDEO_MODE_PAL60: u32 = 1;
pub const VIDEO_MODE_NTSC: u32 = 2;
pub const VIDEO_MODE_YUV_480P: u32 = 3;
pub const VIDEO_MODE_YUV_720P: u32 = 4;
pub const VIDEO_MODE_HDMI_720P: u32 = 5;
pub const VIDEO_MODE_VGA_640x480: u32 = 6;
pub const VIDEO_MODE_VGA_1024x768: u32 = 7;
pub const VIDEO_MODE_VGA_1280x720: u32 = 8;
pub const VIDEO_MODE_VGA_1280x768: u32 = 9;
pub const VIDEO_MODE_VGA_1280x1024: u32 = 10;
pub const VIDEO_MODE_VGA_1360x768: u32 = 11;
pub const VIDEO_MODE_VGA_1440x900: u32 = 12;
pub const VIDEO_MODE_COUNT: u32 = 13;
pub const D1CRTC_UPDATE_LOCK: u32 = 24808;
pub const DCP_LB_DATA_GAP_BETWEEN_CHUNK: u32 = 27836;
pub const D1CRTC_DOUBLE_BUFFER_CONTROL: u32 = 24812;
pub const D1CRTC_V_TOTAL: u32 = 24608;
pub const D1CRTC_H_TOTAL: u32 = 24576;
pub const D1CRTC_H_SYNC_B: u32 = 24592;
pub const D1CRTC_H_BLANK_START_END: u32 = 24580;
pub const D1CRTC_H_SYNC_B_CNTL: u32 = 24596;
pub const D1CRTC_H_SYNC_A: u32 = 24584;
pub const D1CRTC_V_SYNC_B: u32 = 24624;
pub const D1CRTC_H_SYNC_A_CNTL: u32 = 24588;
pub const D1CRTC_MVP_INBAND_CNTL_CAP: u32 = 24652;
pub const D1CRTC_MVP_INBAND_CNTL_INSERT: u32 = 24656;
pub const D1CRTC_MVP_FIFO_STATUS: u32 = 24644;
pub const D1CRTC_MVP_SLAVE_STATUS: u32 = 24648;
pub const D1GRPH_UPDATE: u32 = 24900;
pub const D1GRPH_PITCH: u32 = 24864;
pub const D1GRPH_CONTROL: u32 = 24836;
pub const D1GRPH_LUT_SEL: u32 = 24840;
pub const D1GRPH_SURFACE_OFFSET_X: u32 = 24868;
pub const D1GRPH_SURFACE_OFFSET_Y: u32 = 24872;
pub const D1GRPH_X_START: u32 = 24876;
pub const D1GRPH_Y_START: u32 = 24880;
pub const D1GRPH_X_END: u32 = 24884;
pub const D1GRPH_Y_END: u32 = 24888;
pub const D1GRPH_PRIMARY_SURFACE_ADDRESS: u32 = 24848;
pub const D1GRPH_ENABLE: u32 = 24832;
pub const DC_LUT_PWL_DATA: u32 = 25744;
pub const AVIVO_D1SCL_UPDATE: u32 = 26060;
pub const AVIVO_D1SCL_SCALER_ENABLE: u32 = 26000;
pub const AVIVO_D1MODE_VIEWPORT_START: u32 = 25984;
pub const AVIVO_D1MODE_VIEWPORT_SIZE: u32 = 25988;
pub const AVIVO_D1MODE_DATA_FORMAT: u32 = 25896;
pub const D1GRPH_FLIP_CONTROL: u32 = 24904;
pub const AVIVO_D1SCL_SCALER_TAP_CONTROL: u32 = 26004;
pub const DC_LUTA_CONTROL: u32 = 25792;
pub const DC_LUT_RW_INDEX: u32 = 25736;
pub const DC_LUT_RW_MODE: u32 = 25732;
pub const DC_LUT_WRITE_EN_MASK: u32 = 25756;
pub const DC_LUT_AUTOFILL: u32 = 25760;
pub const D1CRTC_MVP_CONTROL1: u32 = 24632;
pub const D1CRTC_MVP_CONTROL2: u32 = 24636;
pub const D1CRTC_MVP_FIFO_CONTROL: u32 = 24640;
pub const AVIVO_D1CRTC_V_BLANK_START_END: u32 = 24612;
pub const D1CRTC_MVP_INBAND_CNTL_INSERT_TIMER: u32 = 24660;
pub const D1CRTC_MVP_BLACK_KEYER: u32 = 24664;
pub const D1CRTC_TRIGA_CNTL: u32 = 24672;
pub const D1CRTC_TRIGA_MANUAL_TRIG: u32 = 24676;
pub const D1CRTC_TRIGB_CNTL: u32 = 24680;
pub const AVIVO_D1MODE_DESKTOP_HEIGHT: u32 = 25900;
pub const D1GRPH_COLOR_MATRIX_TRANSFORMATION_CNTL: u32 = 25472;
pub const D1COLOR_MATRIX_COEF_1_1: u32 = 25476;
pub const D1COLOR_MATRIX_COEF_1_2: u32 = 25480;
pub const D1COLOR_MATRIX_COEF_1_3: u32 = 25484;
pub const D1COLOR_MATRIX_COEF_1_4: u32 = 25488;
pub const D1COLOR_MATRIX_COEF_2_1: u32 = 25492;
pub const D1COLOR_MATRIX_COEF_2_2: u32 = 25496;
pub const D1COLOR_MATRIX_COEF_2_3: u32 = 25500;
pub const D1COLOR_MATRIX_COEF_2_4: u32 = 25504;
pub const D1COLOR_MATRIX_COEF_3_1: u32 = 25508;
pub const D1COLOR_MATRIX_COEF_3_2: u32 = 25512;
pub const D1COLOR_MATRIX_COEF_3_3: u32 = 25516;
pub const D1COLOR_MATRIX_COEF_3_4: u32 = 25520;
unsafe extern "C" {
    pub fn xenos_is_initialized() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn xenos_init(videoMode: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn xenos_is_overscan() -> ::std::os::raw::c_int;
}
