/* automatically generated by rust-bindgen 0.72.1 */

pub const VIDEO_MODE_AUTO: i32 = -1;
pub const VIDEO_MODE_PAL50: u32 = 0;
pub const VIDEO_MODE_PAL60: u32 = 1;
pub const VIDEO_MODE_NTSC: u32 = 2;
pub const VIDEO_MODE_YUV_480P: u32 = 3;
pub const VIDEO_MODE_YUV_720P: u32 = 4;
pub const VIDEO_MODE_HDMI_720P: u32 = 5;
pub const VIDEO_MODE_VGA_640x480: u32 = 6;
pub const VIDEO_MODE_VGA_1024x768: u32 = 7;
pub const VIDEO_MODE_VGA_1280x720: u32 = 8;
pub const VIDEO_MODE_VGA_1280x768: u32 = 9;
pub const VIDEO_MODE_VGA_1280x1024: u32 = 10;
pub const VIDEO_MODE_VGA_1360x768: u32 = 11;
pub const VIDEO_MODE_VGA_1440x900: u32 = 12;
pub const VIDEO_MODE_COUNT: u32 = 13;
