/* automatically generated by rust-bindgen 0.72.1 */

pub const XENON_SPEED_1_3: u32 = 4;
pub const XENON_SPEED_1_2: u32 = 3;
pub const XENON_SPEED_3_2: u32 = 2;
pub const XENON_SPEED_FULL: u32 = 1;
unsafe extern "C" {
    pub fn xenon_thread_startup();
}
unsafe extern "C" {
    pub fn xenon_make_it_faster(speed: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn xenon_run_thread_task(
        thread: ::std::os::raw::c_int,
        stack: *mut ::std::os::raw::c_void,
        task: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn xenon_is_thread_task_running(thread: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn xenon_sleep_thread(thread: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn xenon_set_single_thread_mode();
}
