/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn usb_init() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn usb_shutdown();
}
unsafe extern "C" {
    pub fn usb_do_poll();
}
