/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn telnet_console_init();
}
unsafe extern "C" {
    pub fn telnet_console_tx_print(buf: *const ::std::os::raw::c_char, bc: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn telnet_console_close();
}
