/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn udelay(arg1: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn mdelay(arg1: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn delay(arg1: ::std::os::raw::c_int);
}
