/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn rc4_init(
        state: *mut ::std::os::raw::c_uchar,
        key: *mut ::std::os::raw::c_uchar,
        len: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rc4_crypt(
        state: *mut ::std::os::raw::c_uchar,
        data: *mut ::std::os::raw::c_uchar,
        len: ::std::os::raw::c_int,
    );
}
