/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn atomic_inc(v: *mut ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn atomic_dec(v: *mut ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn atomic_clearset(
        v: *mut ::std::os::raw::c_uint,
        andc: ::std::os::raw::c_uint,
        or_: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn lock(lock: *mut ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn unlock(lock: *mut ::std::os::raw::c_uint);
}
