/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn xenon_sound_init();
}
unsafe extern "C" {
    pub fn xenon_sound_submit(data: *mut ::std::os::raw::c_void, len: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn xenon_sound_get_free() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn xenon_sound_get_unplayed() -> ::std::os::raw::c_int;
}
