/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn putch(c: ::std::os::raw::c_uchar);
}
unsafe extern "C" {
    pub fn kbhit() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn getch() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn uart_puts(s: *mut ::std::os::raw::c_uchar);
}
